remote_theme: rohanchandra/type-theme

collections:
  aktivity:
    sort_by: order



# SITE CONFIGURATION
baseurl: "/"
url: "https://openczeg.github.io/"



# THEME-SPECIFIC CONFIGURATION
theme_settings:
  site_navigation_sort: "order"
  # Meta
  title: "#OPENCZEG: Otevřený egovernment v ČR"
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "#openczeg - otevřený egovernment v ČR"

  # Header and footer text
  header_text: >
    
  header_text_feature_image:
  footer_text: >
    <p>© 2020 Opensource aliance</p>

  # Icons
  rss: true
  email_address: 
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  gitlab:
  github: openczeg
  gitter:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: openczeg
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Najdete nás na"
  str_rss_follow: "RSS kanál"
  str_email: "Email"
  str_next_post: "Další příspěvek"
  str_previous_post: "Předchozí příspěvek"
  str_next_page: "Další stránka"
  str_previous_page: "Předchozí stránka"
  str_continue_reading: "Čtěte dál..."
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "Nic jsme nenašli."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
